server.port=8083
spring.application.name=appointment-service

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/hospital_appointments

# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
